### ISSUE TITLE
Inconsistent view modes across Addons and Music

### ISSUE THREAD

**Issue by bryanbrazil** [jeroenpardon/skin.refocus#37]
I've noticed inconsistencies in the availability of view modes in Addons and Music. For example:

Music Addons: The only available view modes are List and Tiles

Video Addons: Available view modes are List, Slide, Thumbnails, and Tiles. Thumbnails has an option for a large or small grid.

Program Addons and Music (Artists/Albums): Available view modes are List, Slide, Thumbnails, and Tiles. However, Thumbnails does not have an option for a large or small grid.

**Comment by jeroenpardon** [comment]
They're inconsistencies by choice mostly. The lack of standards with regards to art types, available metadata and such make dealing with add-ons in Kodi a pita frankly. 

The available Kodi standard content types like movies, tvshows, episodes, artists, albums are used by add-ons even though they don't provide the art types and metadata that warrant using these content types. 

It was a very conscious decision for reFocus not to have "unisex" viewtypes or showing viewtypes  that are clearly not suited for the content type being listed (resulting in things like stretched thumbnails, empty labels, etc).

So I look at every viewtype and decide whether or not it actually offers something extra. The small and large grids, Slide and such are really aimed at content listings actually benefiting from that extra available space. I have a bunch of music add-on installed purely for testing and none of them actually offer metadata that would benefit from these viewtypes imo. 

I'll take another critical look at this, but inconsistencies are bound to remain unfortunately.  

It's a bit hard to explain my reasoning behind this without making this even more boring, but I hope you can make some sense from it ;)
