### ISSUE TITLE
Kodi manual install fails

### ISSUE THREAD

**Issue by landscribe** [jeroenpardon/skin.refocus#39]
Followed manual install instructions to d/l zip file (https://github.com/jeroenpardon/skin.refocus/archive/master.zip) and install manually..
get error in Kodi saying add-on is missing files, and install/enabling skin fails.

**Comment by jeroenpardon** [comment]
Please refer to the installation guide and user forum to discuss installation issues. Make sure you have (the correct versions of) all required add-ons. This is not related to development.
