### ISSUE TITLE
Visualisation - Presets empty

### ISSUE THREAD

**Issue by Tadly** [jeroenpardon/skin.refocus#54]
The presets list for visualisation is always empty.
Don't know what else to say ^^

cheers,
Tadly

**Comment by Tadly** [comment]
I actually should have added that I'm on Kodi Helix.
Haven't tested the other versions

**Comment by jeroenpardon** [comment]
merged, so closing this. In Jarvis this windows is actually deprecated. The select dialog is used instead.
