### ISSUE TITLE
Font size for a screensaver

### ISSUE THREAD

**Issue by vdb86** [jeroenpardon/skin.refocus#59]
Hi jeroenpardon, I've made a screensaver for Kodi, unfortunately addons can't use their own Fonts and we have to rely on skins to provide them.
Would you please add a font size to refocus?
The name doesn't matter, but I would prefer something like clock.
The font size should be 85.
If you need any more information please let me know.
Thank you for your help!

**Comment by jeroenpardon** [comment]
merged, so closing this issue. thanks!

**Comment by vdb86** [comment]
Awesome, thank you!
