### ISSUE TITLE
Where is the file browser?

### ISSUE THREAD

**Issue by ProfessorKaos64** [jeroenpardon/skin.refocus#60]
I've looked up and down for this in settings, where is it? Is it included?

**Comment by jeroenpardon** [comment]
add it in the home menu configuration. this is not a forum.

**Comment by ProfessorKaos64** [comment]
Sorry..didn't see this in the FAQ...

**Comment by kb0n** [comment]
Either way, this area is for reporting issues/bugs ;) If you have regular questions, you should use a forum, mailing-list, or any other means mentioned by the developer for asking questions. Just an advice for the future :)
