### ISSUE TITLE
Audio Plugin - Available Views

### ISSUE THREAD

**Issue by Tadly** [jeroenpardon/skin.refocus#61]
So I'm working on a audio plugin for kodi and realized that the "Available Views" only include "List" and when the content is set to "songs" it includes "Thumbnails" as well.

As just said, I set the content properly to either "artists", "albums" or "songs" which does affect the listitem style but doesn't give me any additional views.

I tried finding that bit in the source and fix it but as I'm not a skinner, I failed really hard ^^

Would be nice to see all the available views no matter where you are. At the end it's a user choice what view he things fits best.

If you could point me in the right direction I can try and change it myself :)

**Comment by jeroenpardon** [comment]
I'll have to get back to you when I get into working on the Jarvis version
a bit more, I am a bit rusty at the moment :) Generally speaking I agree
with you abou t the user choice. However unlike many skins refocus does not
use viewtypes that are "one size fits all" they are consciously tailor made
to the specific content type. But let me look into what I can do ;)

**Comment by Tadly** [comment]
Ah I see. Yeah that makes sense. :)

I was just expecting to get the same viewtypes for e.g. when browsing "Artists" in library mode and browsing my plugins "Artists" when the content is set to "artists" (same goes for albums and songs obviously)

Nice to see you back btw. ;) almost got worried ^^

**Comment by jeroenpardon** [comment]
Well, that certainly seems doable and logical. I'll just have to see what
kind of conditions are needed to be set. Do you have a release or test
version available so I can experiment? I never really consciously left,
there's too little time available for all I need or want to do ;) trying to
get into the groove of coding again. It will be a while before I have
caught up I'm afraid

**Comment by Tadly** [comment]
I know that feeling just to well. I'm bouncing between 6 private projects right now ^^

Well... the plugin I'm working on is for google music, requires all-access and currently holds features that aren't supposed for public I'm afraid. Not sure if this addon will be public ever ^^
If you happen to have gmusic and all-access I might be able to give you a version because I'm nice like that. If you don't, you can't really use it for testing :/

I'm sure you'll get the grip of it again.. at some point :D
Just don't let the project die. Therefore it is to perfect of a skin ;)
(even though I wish tv.show.next.aired wouldn't be a dependencie but that's just me ^^)

**Comment by Tadly** [comment]
Just thought of something..
I could in theory create a small dummy addon displaying fake data if you'd like me to. (could include dummy videos as well)

**Comment by Tadly** [comment]
Oh wow.. mmh..

So I quickly made a dummy addon and while testing it I realized that that dummy-addon I get more viewtypes than with my other one ._.

Looks like I messed up somewhere in my original addon :/

**Comment by jeroenpardon** [comment]
don't you hate when that happens ;) Not sure if a dummy add-on is needed for me tbh, I would assume testing with some other music add-on will bring me a long way. It's just that I don't really use Kodi for music, so it would have been a way to do some specific testing. Looking through the Jarvis changes the music library is finally starting to catch up with the video library changes in XBMC 10.0 ;) Didn't look into the specifics though. So, what I'm trying to say I guess is I will have to check all the conditions for music content anyway :)

**Comment by Tadly** [comment]
you bet I do ^^
That's fine. The dummy add-on help at least one (me) of us and now I know that something else is fishy ^^ (still.. I did copy&paste code. So strange)

Looking forward to jarvis :)
Also you got some interesting new things in master like the new info-view for videos (missing runtime though :D)
Can't wait for a official refocus update :)

**Comment by Tadly** [comment]
Hm.. now it's getting strange.
When navigation into my dummy addon I still have all viewtypes. If I than go into my gmusic addon I see all availbale views as well.
But as soon as I go out and back in again there all gone ._.

I guess that's Kodi caching something they shouldn't ^^

But as it stands, I still have no clue whatsoever why it's not working in gmusic but in my dummy addon :/

**Comment by jeroenpardon** [comment]
Working through the music library now. I'll let you know when I think most of the Jarvis changes regarding music have been taken care of.

**Comment by Tadly** [comment]
Awesome, thanks :)
I'm still clueless to what's going on :/

**Comment by Tadly** [comment]
I finally know what's different! Well... sort of
The ONLY thing a kept doing differently is the "location" from where I opened the add-ons.

I added a shortcut to the home-menu (for easier access) for my gmusic add-on. My dummy add-on however I always opened from `(Home screen) Music -> (submenu) Add-ons -> Dummy Addon`
If I do the same with my gmusic addon, I see all views-types too.

Now the question is.. what the heck is causing that? :D

btw. yes, as soon as I create a shortcut for my dummy addon on the home screen, it stops working too

**Comment by jeroenpardon** [comment]
So, if you add it to the homescreen you get all the viewtypes in both add-ons? But not when you use the add-ons entry in the music submenu to go to the add-on browser, and then navigate to the add-on?

Not sure what could be causing that really. It's not something I can reproduce with other add-ons but then again I am using my development version. Any chance you could grab a git build and check if the problem is present in there too?

**Comment by Tadly** [comment]
Can confirm, works with Kodi 16 and master :)
So if you want we can close that issue now.

Thanks a lot for the continues help and keep up your awesome work! :)

**Comment by jeroenpardon** [comment]
oh, that's great to hear, glad you have it working properly now :)
