### ISSUE TITLE
How to have transparency on the menu?

### ISSUE THREAD

**Issue by oblitum** [jeroenpardon/skin.refocus#65]
Hi, I really enjoy this skin, it's minimalist and light, it's my choice on my OpenELEC system. I have only one caveat, I'd really like to have a bit of alpha on the menu (I use the horizontal one). I've checked the wiki that it's not supported, so, sorry to ask for it. For me, it can be any configuration in any file of the skin, just some alpha setting, it doesn't need to be on the menu (which could indeed be an option to be added later).

**Comment by jeroenpardon** [comment]
you're going to need to mod it yourself. Ask around on the forum, not here.

**Comment by oblitum** [comment]
Nevermind, I just grep'ed and changed colors on `colors/defaults.xml`, it worked.
