### ISSUE TITLE
Crash: Pressing Back on Music-OSD

### ISSUE THREAD

**Issue by Tadly** [jeroenpardon/skin.refocus#69]
Steps to reproduce:
 1. Play music
 2. Open OSD Control
 3. Focus one of the list entries (with the media controls on top it doesn't happen)
 4. Press *back* on the keyboard (esc works just fine)

This works fine with videos.

That's the last thing in my kodi.log
```
...
07:39:28 T:139971336648768   ERROR: Window Translator: Can't find window artists
07:39:28 T:139971336648768   ERROR: GetDirectory - Error getting MusicLibrary
07:39:28 T:139971336648768   ERROR: CGUIMediaWindow::GetDirectory(MusicLibrary) failed
```

Oh and starting kodi via gdb:
```
Thread 1 "kodi.bin" received signal SIGSEGV, Segmentation fault.
0x000000000091b063 in CGUIControlGroup::GetFirstFocusableControl(int) ()
```

**Comment by jeroenpardon** [comment]
Confirmed and fixed in 634858bc23d341c2c3d235db81370131477f84aa

Cheers for the report!
