### ISSUE TITLE
Dependency errors

### ISSUE THREAD

**Issue by kgoerbig** [jeroenpardon/skin.refocus#71]
I'm attempting to upgrade from 3.01 within Kodi 16.1 (Using OSMC on Raspi PI) through a normal update, and I am getting dependency errors. 

I backed up refocus, and them uninstalled it, I then removed all refocus directories in userdata, and then attemped a fresh install of 3.21 through Kodi install menu, and received the same error.

I also tried via 3.21 zip from github, and receive the same error.

**Comment by jeroenpardon** [comment]
https://github.com/jeroenpardon/skin.refocus/wiki#faq
