### ISSUE TITLE
[CR] tag unsupported 

### ISSUE THREAD

**Issue by nicoserafino** [jeroenpardon/skin.refocus#73]
Hi everybody,
<br />reFocus is perfect for me. It is very customizabile!
<br />However **it does not support [CR] tags** in order to show the second line of text in a item of a list.
<br />Will this function be included? If not, may I edit the code in order to support [CR] tags on my own?
<br />Thank you!
<br />
<br />My issue is found here: kodilive addon

**Comment by jeroenpardon** [comment]
There is nothing for reFocus to support, and there is nothing to include. It uses Kodi xml syntax like any other skin. If you're using CR and something isn't working as intended, you are doing something wrong.
